# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7289bba6a10b4b6bc831473c9cb646154fd89aa22abc21f60c47bd5c4699446ef2e71abf82ad0c274f2ab7726086c095953c5483e16ec66d92c5aca34de292b

test:
  secret_key_base: a66fb0117705bf85fe5e53bb00504cf080d0d4b2f59def3d425ef4f35c23a19ab8505062be43b189bacab257f8feac6447cbc4da7829a5a1d169f2c74c769020

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
